# Generated by Django 5.1.4 on 2025-06-28 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('project_name', models.CharField(max_length=255)),
                ('encryption_status', models.BooleanField(default=False)),
                ('deposit_payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
